version: '3'
services:
  web:
    build: .
    ports:
    - "4000:4000"
    volumes:
    - .:/src
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
