version: '3'
services:
  web:
    build: .
    networks:
      - katzefudder
    ports:
    - "4000:4000"
    volumes:
    - .:/src
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    networks:
      - katzefudder
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /tmp/cache:/cache
    depends_on:
      - web
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80

networks:
  katzefudder:
